title: "Jose Márquez Jaramillo"
author: "Jose Márquez Jaramillo"
description: "Quantitative Developer"
url: "https://josemarquez.us"
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
permalink: pretty
